# Generated by Django 3.1.4 on 2021-01-02 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userinfo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='orm_test.userinfo'),
        ),
    ]
